### ISSUE TITLE
BlockexplorerApplication 기동시, "Received AlertMessage before version handshake is complete." 발생

### ISSUE THREAD

**Issue by jdlee726** [epitomecl/kmp-server#29]
```
2018-07-19 11:49:36.555  WARN 136248 --- [ioClientManager] org.bitcoinj.core.PeerSocketHandler      : [64.151.71.52]:18333 - 

org.bitcoinj.core.ProtocolException: Received AlertMessage before version handshake is complete.
	at org.bitcoinj.core.Peer.processMessage(Peer.java:478) ~[bitcoinj-core-0.14.7.jar:na]
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184) ~[bitcoinj-core-0.14.7.jar:na]
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [bitcoinj-core-0.14.7.jar:na]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoinj-core-0.14.7.jar:na]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.14.7.jar:na]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) [guava-23.5-android.jar:na]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [guava-23.5-android.jar:na]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) [bitcoinj-core-0.14.7.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
```

**Comment by jdlee726** [comment]
org.bitcoinj.core.PeerGroup 사용으로 인한 정상 동작
