### ISSUE TITLE
BlockexplorerApplication 기동시, "org.bitcoinj.net.NioClientManager        : Failed to connect with exception: java.net.ConnectException: Connection refused: no further information" 발생

### ISSUE THREAD

**Issue by jdlee726** [epitomecl/kmp-server#31]
```
2018-07-19 11:49:37.819  WARN 136248 --- [ioClientManager] org.bitcoinj.net.NioClientManager        : Failed to connect with exception: java.net.ConnectException: Connection refused: no further information

java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:na]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64) [bitcoinj-core-0.14.7.jar:na]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoinj-core-0.14.7.jar:na]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66) [guava-23.5-android.jar:na]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [guava-23.5-android.jar:na]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) [bitcoinj-core-0.14.7.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
```

**Comment by jdlee726** [comment]
org.bitcoinj.core.PeerGroup 사용으로 인한 정상 동작
